[
    {
        "id": 615854510,
        "name": "exploit-CVE-2020-24815.py",
        "full_name": "ziadanbari2021\/exploit-CVE-2020-24815.py",
        "owner": {
            "login": "ziadanbari2021",
            "id": 111196316,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/111196316?v=4",
            "html_url": "https:\/\/github.com\/ziadanbari2021"
        },
        "html_url": "https:\/\/github.com\/ziadanbari2021\/exploit-CVE-2020-24815.py",
        "description": null,
        "fork": false,
        "created_at": "2023-03-18T21:42:29Z",
        "updated_at": "2023-03-18T21:46:31Z",
        "pushed_at": "2023-03-18T22:49:49Z",
        "stargazers_count": 0,
        "watchers_count": 0,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "watchers": 0,
        "score": 0
    }
]