[
    {
        "id": 413773987,
        "name": "CVE-2021-32285",
        "full_name": "AKIA27TACKEDYE76PUGU\/CVE-2021-32285",
        "owner": {
            "login": "AKIA27TACKEDYE76PUGU",
            "id": 86665563,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/86665563?v=4",
            "html_url": "https:\/\/github.com\/AKIA27TACKEDYE76PUGU"
        },
        "html_url": "https:\/\/github.com\/AKIA27TACKEDYE76PUGU\/CVE-2021-32285",
        "description": "PoC for exploiting CVE-2021-32285 : An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.",
        "fork": false,
        "created_at": "2021-10-05T10:40:01Z",
        "updated_at": "2021-10-05T10:40:09Z",
        "pushed_at": "2021-10-05T10:40:06Z",
        "stargazers_count": 0,
        "watchers_count": 0,
        "forks_count": 0,
        "allow_forking": true,
        "visibility": "public",
        "forks": 0,
        "watchers": 0,
        "score": 0
    }
]